In [1]:
import numpy as np


In [2]:
myarr = np.array([3,46,5,44], np.int8)

In [3]:
myarr

array([ 3, 46,  5, 44], dtype=int8)

In [4]:
myarr = np.array([[3,45,76,7]], np.int32)  #its a 2d array now but only sinle brackets then 1d array an will eventually return the value at the index position

In [5]:
myarr[0,1]

np.int32(45)

In [6]:
myarr[0,1] = 32

In [7]:
myarr

array([[ 3, 32, 76,  7]], dtype=int32)

# Array craetion: Conversion from python structures

In [8]:
listarray = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [9]:
listarray

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [10]:
listarray.dtype

dtype('int64')

In [11]:
listarray.shape

(3, 3)

In [12]:
listarray.size

9

In [13]:
np.array({73,65,85})

array({73, 65, 85}, dtype=object)

**Intrinsic numpy array creation**

In [16]:
zeros = np.zeros((2,4))

In [17]:
zeros

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [81]:
np.random.random((3,5))

array([[0.50105958, 0.54857761, 0.31175628, 0.41269459, 0.65441839],
       [0.01387051, 0.44839825, 0.58922701, 0.87151099, 0.8516255 ],
       [0.79705692, 0.29363135, 0.10970569, 0.09045189, 0.8485186 ]])

In [18]:
rng = np.arange(15)

In [20]:
rng

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [21]:
lnspc = np.linspace(1,50,10)

In [22]:
lnspc

array([ 1.        ,  6.44444444, 11.88888889, 17.33333333, 22.77777778,
       28.22222222, 33.66666667, 39.11111111, 44.55555556, 50.        ])

In [23]:
emp = np.empty((4,6))

In [24]:
emp

array([[6.23042070e-307, 4.67296746e-307, 1.69121096e-306,
        1.24610994e-306, 1.42413555e-306, 1.78019082e-306],
       [1.37959740e-306, 6.23057349e-307, 1.02360935e-306,
        1.69120416e-306, 1.78022342e-306, 6.23058028e-307],
       [1.06811422e-306, 9.45699680e-308, 1.11258854e-306,
        1.11261502e-306, 1.42410839e-306, 7.56597770e-307],
       [6.23059726e-307, 1.42419530e-306, 6.89805151e-307,
        1.78020169e-306, 1.42410974e-306, 8.34451927e-308]])

In [26]:
empLike = np.empty_like(lnspc)

In [27]:
empLike

array([ 1.        ,  6.44444444, 11.88888889, 17.33333333, 22.77777778,
       28.22222222, 33.66666667, 39.11111111, 44.55555556, 50.        ])

In [28]:
id = np.identity(28)

In [29]:
id

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0

In [30]:
id.shape

(28, 28)

In [31]:
arr = np.arange(99)

In [32]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [33]:
arr.reshape(3,33)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32],
       [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
        49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64,
        65],
       [66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
        82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
        98]])

In [35]:
arr.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [36]:
arr.shape

(99,)

**Array axis**

In [37]:
x = [[1,23,3], [3,5,6],[3,67,97]]

In [39]:
ar = np.array(x)

In [40]:
ar

array([[ 1, 23,  3],
       [ 3,  5,  6],
       [ 3, 67, 97]])

In [92]:
#0 --> col #1 --> row

In [41]:
ar.sum(axis=0)   #sum column-wise 

array([  7,  95, 106])

In [42]:
ar.sum(axis=1)   #sum row-wise

array([ 27,  14, 167])

In [43]:
ar.T

array([[ 1,  3,  3],
       [23,  5, 67],
       [ 3,  6, 97]])

In [44]:
ar.flat

In [45]:
for item in ar.flat:
    print(item)

1
23
3
3
5
6
3
67
97


In [46]:
ar.ndim  #tells about the number of dimension

2

In [47]:
ar.size

9

In [48]:
ar.nbytes  #tells about total bytes consumed

72

In [49]:
one = np.array([1,3,4,56,7,234])

In [50]:
one.argmax()   #gives the index value of max valued number

np.int64(5)

In [51]:
one.argmin()    #gives the index value of min valued number

np.int64(0)

In [52]:
one.argsort()   #gives the sorted manner of index values in the ascending order

array([0, 1, 2, 4, 3, 5])

In [53]:
ar

array([[ 1, 23,  3],
       [ 3,  5,  6],
       [ 3, 67, 97]])

In [56]:
ar.argmin()

np.int64(0)

In [57]:
ar.argmax()

np.int64(8)

In [58]:
ar.argmax(axis=0)

array([1, 2, 2])

In [59]:
ar.argmax(axis=1)

array([1, 2, 2])

In [60]:
ar.argsort(axis=0)

array([[0, 1, 0],
       [1, 0, 1],
       [2, 2, 2]])

In [61]:
ar.argsort(axis=1)

array([[0, 2, 1],
       [0, 1, 2],
       [0, 1, 2]])

In [62]:
ar.ravel()

array([ 1, 23,  3,  3,  5,  6,  3, 67, 97])

In [63]:
ar2 = np.array([[5, 2, 1],
       [2, 1, 2],
       [8, 1, 2]])

In [64]:
ar +ar2

array([[ 6, 25,  4],
       [ 5,  6,  8],
       [11, 68, 99]])

In [65]:
ar *ar2

array([[  5,  46,   3],
       [  6,   5,  12],
       [ 24,  67, 194]])

In [66]:
np.sqrt(ar)

array([[1.        , 4.79583152, 1.73205081],
       [1.73205081, 2.23606798, 2.44948974],
       [1.73205081, 8.18535277, 9.8488578 ]])

In [67]:
ar.sum()

np.int64(208)

In [68]:
ar.max()

np.int64(97)

In [69]:
ar

array([[ 1, 23,  3],
       [ 3,  5,  6],
       [ 3, 67, 97]])

In [70]:
np.where(ar>5)

(array([0, 1, 2, 2]), array([1, 2, 1, 2]))

In [71]:
np.count_nonzero(ar)

9

In [72]:
np.nonzero(ar)

(array([0, 0, 0, 1, 1, 1, 2, 2, 2]), array([0, 1, 2, 0, 1, 2, 0, 1, 2]))

In [73]:
import sys

In [74]:
py_arr = [0,4,7,3]

In [75]:
np_arr = np.array(py_arr)

In [76]:
sys.getsizeof(1) * len(py_arr)

112

In [78]:
np_arr.itemsize * np_arr.size

32

In [80]:
np_arr.tolist()

[0, 4, 7, 3]

**Changing Datatypes**

In [82]:
a3 = np.arange(8).reshape(2,2,2)

In [83]:
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [84]:
a3.dtype

dtype('int64')

In [85]:
a3.astype(np.int32)    #reduced memory size

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]], dtype=int32)

**Array Ops -- Scalar Ops**

In [86]:
ar*2   #all the arithmetic operators

array([[  2,  46,   6],
       [  6,  10,  12],
       [  6, 134, 194]])

In [87]:
ar>12   #all the relational operators

array([[False,  True, False],
       [False, False, False],
       [False,  True,  True]])

**Array ops -- Vector ops**

In [88]:
ar + a3   #ops between two different matrices 

ValueError: operands could not be broadcast together with shapes (3,3) (2,2,2) 

**Array Functions**

In [91]:
p = np.random.random((3,3))
p = np.round(ar*100)
p

array([[ 100, 2300,  300],
       [ 300,  500,  600],
       [ 300, 6700, 9700]])

In [95]:
#mean / median / std / var
np.mean(p)


np.float64(2311.1111111111113)

In [96]:
np.mean(p, axis =0)

array([ 233.33333333, 3166.66666667, 3533.33333333])

**Dot product**

In [101]:
q = np.arange(12).reshape(3,4)
r = np.arange(12, 24).reshape(4,3)

np.dot(q, r)

array([[114, 120, 126],
       [378, 400, 422],
       [642, 680, 718]])

**log and exponents**

In [103]:
np.log(q)

C:\Users\Dell\AppData\Local\Temp\ipykernel_14384\133699003.py:2: RuntimeWarning: divide by zero encountered in log
  np.log(q)


array([[      -inf, 0.        , 0.69314718, 1.09861229],
       [1.38629436, 1.60943791, 1.79175947, 1.94591015],
       [2.07944154, 2.19722458, 2.30258509, 2.39789527]])

In [104]:
np.exp(r)

array([[1.62754791e+05, 4.42413392e+05, 1.20260428e+06],
       [3.26901737e+06, 8.88611052e+06, 2.41549528e+07],
       [6.56599691e+07, 1.78482301e+08, 4.85165195e+08],
       [1.31881573e+09, 3.58491285e+09, 9.74480345e+09]])

**Round / floor / ceil**

In [105]:
np.round(np.random.random((2,3))*100)  #rounding off to the nearest integer

array([[86., 62., 86.],
       [20., 75., 53.]])

In [106]:
np.floor(np.random.random((2,3))*100)   #rounding off to the nearest integer backwards

array([[55., 70., 35.],
       [15., 65., 34.]])

In [107]:
np.ceil(np.random.random((2,3))*100)    #rounding off to the nearest integer frontwards

array([[79., 16., 41.],
       [42., 88., 29.]])

**Indexing and Slicing**

In [112]:
x = np.arange(10)
y = np.arange(12).reshape(3,4)
z = np.arange(8).reshape(2,2,2)


In [109]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [113]:
y

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [114]:
y[1,3]

np.int64(7)

In [115]:
z

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [116]:
z[1,0,1]

np.int64(5)

In [117]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [118]:
x[2:5]

array([2, 3, 4])

In [119]:
y

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [120]:
y[0,:]

array([0, 1, 2, 3])

In [121]:
y[:,2]

array([ 2,  6, 10])

In [122]:
y[1:,1:3]

array([[ 5,  6],
       [ 9, 10]])

In [123]:
y[::2,::3]

array([[ 0,  3],
       [ 8, 11]])

In [124]:
z

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [125]:
z = np.arange(27).reshape(3,3,3)
z

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [126]:
z[1]

array([[ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17]])

In [127]:
z[::2]

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [128]:
z[0,1,:]

array([3, 4, 5])

In [129]:
z[1,:,1]

array([10, 13, 16])

In [130]:
z[2,1:,1:]

array([[22, 23],
       [25, 26]])

In [131]:
z[::2, 0,::2]

array([[ 0,  2],
       [18, 20]])

In [133]:
#iteration

for i in np.nditer(z):
    print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26


**Stacking -- Horizontal and Vertical**

In [134]:
#Horizontal
m = np.arange(12).reshape(3,4)
n = np.arange(12, 24).reshape(3,4)

In [135]:
np.hstack((m,n))

array([[ 0,  1,  2,  3, 12, 13, 14, 15],
       [ 4,  5,  6,  7, 16, 17, 18, 19],
       [ 8,  9, 10, 11, 20, 21, 22, 23]])

In [136]:
# Vertical
np.vstack((m,n))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

**Splitting**

In [137]:
#Horiontal
np.hsplit(m,2)

[array([[0, 1],
        [4, 5],
        [8, 9]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11]])]

In [138]:
#Vertical 
np.vsplit(n,3)

[array([[12, 13, 14, 15]]),
 array([[16, 17, 18, 19]]),
 array([[20, 21, 22, 23]])]